# docker-compose.yml
version: '3.8'

services:
  nvflare-dev:
    image: nvflare-dev:latest
    container_name: nvflare-dev
    working_dir: /workspace
    volumes:
      - .:/workspace
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - "5678:5678"
